import Navbar from '@/components/Navbar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Provider } from './Provider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
	display: 'swap'
})

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<Provider>
				<body className={inter.variable}>
					<Navbar />
					{children}
				</body>
			</Provider>
		</html>
	)
}
